version: "3"
services:
  app:
    container_name: trans-watcher
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    network_mode: host
    logging:
      options:
        max-size: 50m
