name: SSH Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        env:
          VCB_API_URL: ${{ secrets.VCB_API_URL }}
          VCB_USERNAME: ${{ secrets.VCB_USERNAME }}
          VCB_PASSWORD: ${{ secrets.VCB_PASSWORD }}
          VCB_ACCOUNT_NUMBER: ${{ secrets.VCB_ACCOUNT_NUMBER }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Remove the old .env file if it exists
            # sudo rm -f ~/vcb-trans-watchdog/.env

            # Create a new .env file with secrets
            echo "VCB_API_URL=$VCB_API_URL" | sudo tee -a .env 
            echo "VCB_USERNAME=${{ secrets.VCB_USERNAME }}" | sudo tee -a .env 
            echo "VCB_PASSWORD=${{ secrets.VCB_PASSWORD }}" | sudo tee -a .env 
            echo "VCB_ACCOUNT_NUMBER=${{ secrets.VCB_ACCOUNT_NUMBER }}" | sudo tee -a .env 
            echo "DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }}" | sudo tee -a .env 

            # Add any additional deployment commands
            sduo echo "Deploying via SSH..."
            cd ~/vcb-trans-watchdog
            sudo git pull origin main
            # Add any additional commands for deployment
            sudo docker image prune
            sudo docker-compose up -d --no-deps --build
